SRC_NAME = dnspod
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/ardnspod /usr/bin/ardnspod
	$(ROMFSINST) -p +x $(THISDIR)/dnspod.sh /usr/bin/dnspod.sh
